---
apiVersion: v2
name: clabernetes
description: Manage containerlab topologies in a kubernetes cluster
home: https://github.com/cms-lab-core/cms-labs-clabernetes
sources:
  - https://github.com/cms-lab-core/cms-labs-clabernetes
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: BSD-3-Clause
  artifacthub.io/links: |
    - name: support
      url: https://github.com/cms-lab-core/cms-labs-clabernetes/issues
    - name: documentation
      url: https://containerlab.dev/manual/clabernetes/
keywords:
  - network
  - containerlab
maintainers:
  - name: Carl Montanari
    email: carl.r.montanari@gmail.com
    url: https://twitter.com/carlrmontanari
icon: https://gitlab.com/rdodin/pics/-/wikis/uploads/259ce936020a95eb9e78c6f353633587/c9s_logo1-upscale2x-white-tag+font-min.png
type: application
version: 0.0.0
dependencies:
  # being a local (symlinked) dep, no need for version or repo or anything
  - name: clicker
    version: 0.0.0
    condition: clicker.enabled
