---
apiVersion: v2
name: clicker
description: Cl(abernetes t)ick(l)er! For "clicking" on some nodes to perform clabernetes related cluster wide sysctl commands.
home: https://github.com/maintainer64/cms-labs-clabernetes
sources:
  - https://github.com/maintainer64/cms-labs-clabernetes
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: BSD-3-Clause
  artifacthub.io/links: |
    - name: support
      url: https://github.com/maintainer64/cms-labs-clabernetes/issues
keywords:
  - network
  - containerlab
maintainers:
  - name: Carl Montanari
    email: carl.r.montanari@gmail.com
    url: https://twitter.com/carlrmontanari
type: application
version: 0.0.0
dependencies: []
